APTA/Models/Conference.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace APTA.Models
{
    public class Conference
    {
        public int ConferenceId { get; set; }
        [Required]
        [Display(Name = "Conference Name")]
        public string ConferenceName { get; set; }
        [Required]
        [Display(Name = "Conference Description")]
        public string ConferenceDescription { get; set; }
        [Required]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]        
        public DateTime ConferenceDateStart { get; set; }
        [Required]
        [Display(Name = "Finish Date")]
        [DataType(DataType.Date)]        
        public DateTime ConferenceDateEnd { get; set; }

        [Display(Name = "Co-Hosting Organization")]
        public int OrganizationId { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Member> Members { get; set; }

        public Conference()
        {
            Events = new List<Event>();
            Members = new List<Member>();
        }
    }
}

APTA/Controllers/ConferenceController.cs
using APTA.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace APTA.Controllers
{
    public class ConferenceController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();
        // GET: Conference
        public async Task<ActionResult> Index()
        {
            return View(await _context.Conferences.Include(m => m.Members).Include(o => o.Organization).Include(e => e.Events).ToListAsync());
        }
        public ActionResult CreateConference()
        {
            SelectList organizations = new SelectList(_context.Organizations, "OrganizationId", "OrganizationName");
            ViewBag.Organizations = organizations;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CreateConference(Conference conference)
        {
            if (ModelState.IsValid)
            {
                _context.Conferences.Add(conference);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return (CreateConference());
        }

        public async Task<ActionResult> DeleteConference(int id = 0)
        {
            var conference = await _context.Conferences.FindAsync(id);
            if (conference == null || id == 0)
                return HttpNotFound();
            return View(conference);
        }
        [HttpPost, ActionName("DeleteConference")]
        public async Task<ActionResult> DeleteConferenceConfirmed(int id = 0)
        {
            var conference = await _context.Conferences.FindAsync(id);
            if (conference == null || id == 0)
                return HttpNotFound();
            _context.Conferences.Remove(conference);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> EditConference(int id = 0)
        {
            SelectList organizations = new SelectList(_context.Organizations, "OrganizationId", "OrganizationName");
            ViewBag.Organizations = organizations;
            var conference = await _context.Conferences.FindAsync(id);
            if (conference == null || id == 0)
                return HttpNotFound();
            return View(conference);
        }
        [HttpPost]
        public async Task<ActionResult> EditConference(Conference conference)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(conference).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return await EditConference(conference.ConferenceId);
        }
        public async Task<ActionResult> DetailsConference(int id = 0)
        {
            var conference = await _context.Conferences.Include(m => m.Members).Include(o => o.Organization).Include(e => e.Events).SingleOrDefaultAsync(i => i.ConferenceId == id);
            if (conference == null || id == 0)
                return HttpNotFound();
            return View(conference);
        }
        public ActionResult CreateEvent(int id = 0)
        {
            if (id == 0)
                return HttpNotFound();
            Event _event = new Event()
            {
                ConferenceId = id,
            };
            return View(_event);
        }
        [HttpPost]
        public async Task<ActionResult> CreateEvent(Event _event)
        {
            if (ModelState.IsValid)
            {
                _context.Events.Add(_event);
                await _context.SaveChangesAsync();
                return RedirectToAction("DetailsConference", new { id = _event.ConferenceId });
            }
            return CreateEvent(_event.ConferenceId);
        }
        public async Task<ActionResult> EditEvent(int id = 0)
        {
            var _event = await _context.Events.FindAsync(id);
            if (_event == null || id == 0)
                return HttpNotFound();
            return View(_event);
        }
        [HttpPost]
        public async Task<ActionResult> EditEvent(Event _event)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(_event).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction("DetailsConference", new { id = _event.ConferenceId });
            }
            return await EditEvent(_event.EventId);
        }
        public async Task<ActionResult> DeleteEvent(int id = 0)
        {
            var _event = await _context.Events.FindAsync(id);
            if (_event == null || id == 0)
                return HttpNotFound();
            return View(_event);
        }
        [HttpPost, ActionName("DeleteEvent")]
        public async Task<ActionResult> DeleteEventConfirmed(int id)
        {
            var _event = await _context.Events.FindAsync(id);
            if (_event == null || id == 0)
                return HttpNotFound();
            _context.Events.Remove(_event);
            await _context.SaveChangesAsync();
            return RedirectToAction("DetailsConference", new { id = _event.ConferenceId });
        }
        public async Task<ActionResult> AddMember(int id = 0)
        {
            var conference = await _context.Conferences.FindAsync(id);
            if (conference == null || id == 0)
                return HttpNotFound();
            ViewBag.Members = await _context.Members.OrderBy(n => n.MemberFirstName).ToListAsync();
            return View(conference);
        }
        [HttpPost]
        public async Task<ActionResult> AddMember(Conference conference, int[] selectedMembers)
        {
            var tempconference = _context.Conferences.Find(conference.ConferenceId);
            tempconference.Members.Clear();
            if (selectedMembers != null)
            {
                foreach (var m in _context.Members.Where(m => selectedMembers.Contains(m.MemberId)))
                {
                    tempconference.Members.Add(m);
                }
            }

            _context.Entry(tempconference).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return RedirectToAction("DetailsConference", new { id = conference.ConferenceId });

        }
        [HttpPost]
        public async Task<ActionResult> DeleteMember(int mid = 0, int cid = 0)
        {
            if (mid == 0 && cid == 0)
                return HttpNotFound();
            var conference = await _context.Conferences.FindAsync(cid);
            var member = await _context.Members.FindAsync(mid);
            conference.Members.Remove(member);
            _context.Entry(conference).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("DetailsConference", new { id = cid });
        }
    }
}

APTA/Controllers/MemberController.cs
using APTA.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace APTA.Controllers
{
    public class MemberController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        // GET: Members list
        public async Task<ActionResult> Index()
        {
            return View(await _context.Members.Include(c => c.Conferences).ToListAsync());
        }
        public ActionResult CreateMember()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CreateMember(Member member)
        {
            member.MemberRegistrationDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Members.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return CreateMember();
        }
        public async Task<ActionResult> DeleteMember(int id = 0)
        {
            var member = await _context.Members.FindAsync(id);
            if (member == null || id == 0)
                return HttpNotFound();
            return View(member);
        }
        [HttpPost, ActionName("DeleteMember")]
        public async Task<ActionResult> DeleteMemberConfirmed(int id = 0)
        {
            var member = await _context.Members.FindAsync(id);
            if (member == null || id == 0)
                return HttpNotFound();
            _context.Members.Remove(member);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> EditMember(int id = 0)
        {
            var member = await _context.Members.FindAsync(id);
            if (member == null || id == 0)
                return HttpNotFound();
            return View(member);
        }
        [HttpPost]
        public async Task<ActionResult> EditMember(Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(member).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return await EditMember(member.MemberId);
        }
        public async Task<ActionResult> DetailsMember(int id = 0)
        {
            var member = await _context.Members.Include(c => c.Conferences).SingleOrDefaultAsync(i => i.MemberId == id);
            if (member == null || id == 0)
                return HttpNotFound();
            return View(member);
        }
    }
}

APTA/Views/Conference/AddMember.cshtml
@using APTA.Models
@model APTA.Models.Conference

@{
    ViewBag.Title = "Add Members";
}

<h2>Add Member to Conference @Model.ConferenceName</h2>


@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ConferenceId)
     
    @Html.AntiForgeryToken()

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Phone</th>
                <th scope="col">E-mail</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Members != null)
            {
                foreach (Member m in ViewBag.Members)
                {
                    <tr>
                        <th scope="row"><input type="checkbox" name="selectedMembers" value="@m.MemberId" @(Model.Members.Contains(m) ? "checked=\"checked\"" : "") /></th>
                        <td>@m.MemberFirstName @m.MemberLastName</td>
                        <td>@m.MemberPhone</td>
                        <td>@m.MemberEmail</td>
                    </tr>
                }
            }
            else
            {
                foreach (Member m in ViewBag.Members)
                {
                    <tr>
                        <th scope="row"><input type="checkbox" name="selectedMembers" value="@m.MemberId" @*@(Model.Members.Contains(g) ? "checked=\"checked\"" : "")*@ /></th>
                        <td>@m.MemberFirstName @m.MemberLastName</td>
                        <td>@m.MemberPhone</td>
                        <td>@m.MemberEmail</td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back", "DetailsConference", new { id = Model.ConferenceId }, new { @class = "btn btn-dark" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APTA/Views/Conference/CreateConference.cshtml
@model APTA.Models.Conference

@{
    ViewBag.Title = "Create Conference";
}

<h2>Create Conference</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConferenceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConferenceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceDescription, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConferenceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConferenceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceDateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConferenceDateStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConferenceDateStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceDateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConferenceDateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConferenceDateEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10">
                @Html.DropDownList("OrganizationId", ViewBag.Organizations as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APTA/Views/Conference/CreateEvent.cshtml
@model APTA.Models.Event

@{
    ViewBag.Title = "Create Event";
}

<h2>Create Event</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.HiddenFor(model => model.ConferenceId)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="datetime-local" class="form-control text-box single-line" id="EventStart" name="EventStart" />
                @Html.ValidationMessageFor(model => model.EventStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="datetime-local" class="form-control text-box single-line" id="EventEnd" name="EventEnd" />
                @Html.ValidationMessageFor(model => model.EventEnd, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back", "DetailsConference", new { id = Model.ConferenceId }, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APTA/Views/Conference/DeleteConference.cshtml
@model APTA.Models.Conference

@{
    ViewBag.Title = "DeleteConference";
}

<h3>Are you sure you want to delete this Conference: <b>@Model.ConferenceName</b>?</h3>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-dark" })
        </div>
        <br />
    }

APTA/Views/Conference/DeleteEvent.cshtml
@model APTA.Models.Event

@{
    ViewBag.Title = "Delete Event";
}

<h3>Are you sure you want to delete this Event: <b>@Model.EventName</b>?</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        @Html.ActionLink("Back", "DetailsConference", new { id = Model.ConferenceId}, new { @class = "btn btn-dark" })
    </div>
}

APTA/Views/Conference/DetailsConference.cshtml
@model APTA.Models.Conference

@{
    ViewBag.Title = Model.ConferenceName;
}

<h2>@Model.ConferenceName</h2>
<h3>@Model.ConferenceDateStart.ToShortDateString()-@Model.ConferenceDateEnd.ToShortDateString()</h3>
<h3>@Model.ConferenceDescription</h3>

<div>
    <hr />
    <p>
        @Html.ActionLink("Add New Event", "CreateEvent", new { id = Model.ConferenceId }, new { @class = "btn btn-success" })
        @Html.ActionLink("Add New Member", "AddMember", new { id = Model.ConferenceId }, new { @class = "btn btn-success" })
        @Html.ActionLink("Edit", "EditConference", new { id = Model.ConferenceId }, new { @class = "btn btn-dark" })
        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-dark" })
    </p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganizationId):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organization.OrganizationName)
        </dd>
        <dd>
            <b>Adress:</b> @Html.DisplayFor(model => model.Organization.OrganizationAddress)
        </dd>
        <dd>
            <b>Phone:</b> @Html.DisplayFor(model => model.Organization.OrganizationPhone)
        </dd>
        <dd>
            <b>E-mail:</b> @Html.DisplayFor(model => model.Organization.OrganizationEmail)
        </dd>
    </dl>
    <ul class="nav nav-tabs" id="ConfereceTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="events-tab" data-toggle="tab" href="#events" role="tab" aria-controls="events" aria-selected="true">Events</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="members-tab" data-toggle="tab" href="#members" role="tab" aria-controls="members" aria-selected="false">Members</a>
        </li>
    </ul>
    <div class="tab-content" id="ConferenceTabContent">
        <div class="tab-pane fade show active" id="events" role="tabpanel" aria-labelledby="events-tab">
            <table class="table">
                <tbody>
                    @foreach (var item in Model.Events.OrderBy(d => d.EventStart))
                    {
                        <tr>
                            <td>@item.EventStart.ToShortDateString() @item.EventStart.ToShortTimeString()-@item.EventEnd.ToShortTimeString()</td>
                            <td>@item.EventName</td>
                            <td>
                                @Html.ActionLink("Edit", "EditEvent", new { id = item.EventId }) |
                                @Html.ActionLink("Delete", "DeleteEvent", new { id = item.EventId })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="members" role="tabpanel" aria-labelledby="members-tab">
            <table class="table">
                <thead>
                    <tr>

                        <th scope="col">Full Name</th>
                        <th scope="col">Phone</th>
                        <th scope="col">E-mail</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var m in Model.Members.OrderBy(n => n.MemberFirstName))
                    {
                        <tr>
                            <td><a href=@Url.Action("DetailsMember", "Member", new { id = m.MemberId })>@m.MemberFirstName @m.MemberLastName</a></td>
                            <td>@m.MemberPhone</td>
                            <td>@m.MemberEmail</td>
                            <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteMemberModal" onclick="DeleteMember('@m.MemberId', '@Model.ConferenceId')">Delete</button></td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteMemberModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete member</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this Member?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                @using (Html.BeginForm("DeleteMember", "Conference", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="mid" name="mid" value="" />
                    <input type="hidden" id="cid" name="cid" value="" />
                    <input type="submit" class="btn btn-danger" value="Delete">
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function DeleteMember(mId, cId) {            
            $('#mid').val(mId);
            $('#cid').val(cId)
        }
    </script>
}

APTA/Views/Conference/EditConference.cshtml
@model APTA.Models.Conference

@{
    ViewBag.Title = "EditConference";
}

<h2>EditConference</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Conference</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ConferenceId)

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConferenceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConferenceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceDescription, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConferenceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConferenceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceDateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control text-box single-line" id="ConferenceDateStart" name="ConferenceDateStart" value="@Model.ConferenceDateStart.ToString("yyyy-MM-dd")" />
                @*@Html.EditorFor(model => model.ConferenceDateStart, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.ConferenceDateStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConferenceDateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control text-box single-line" id="ConferenceDateEnd" name="ConferenceDateEnd" value="@Model.ConferenceDateEnd.ToString("yyyy-MM-dd")" />
                @*@Html.EditorFor(model => model.ConferenceDateEnd, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.ConferenceDateEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10">
                @Html.DropDownList("OrganizationId", ViewBag.Organizations as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")    
}

APTA/Views/Conference/EditEvent.cshtml
@model APTA.Models.Event

@{
    ViewBag.Title = "EditEvent";
}

<h2>EditEvent</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)
        @Html.HiddenFor(model => model.ConferenceId)

        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="datetime-local" class="form-control text-box single-line" id="EventStart" name="EventStart" value="@Model.EventStart.ToString("yyyy-MM-ddThh:mm")" />
                @Html.ValidationMessageFor(model => model.EventStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="datetime-local" class="form-control text-box single-line" id="EventEnd" name="EventEnd" value="@Model.EventEnd.ToString("yyyy-MM-ddThh:mm")" />
                @Html.ValidationMessageFor(model => model.EventEnd, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back", "DetailsConference", new { id = Model.ConferenceId }, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}